name: interactive_viz
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - zarr
  - xarray
  - geoviews
  - datashader
  - matplotlib
  - panel
  - pandas
  - requests
  - pathlib
  - datetime
  - metpy
  - scipy
  - gradient
  - pip
  - pip:
      - sphinx-pythia-theme
